### ISSUE TITLE
Invalid data length, data must be a multiple of 8 bytes

### ISSUE THREAD

**Issue by CrownlessX** [toddw-as/pyDes#12]
Hi

I stated pad char but still got error:
``Invalid data length, data must be a multiple of 8 bytes``
As I understood - in such cases data length should be increased by X number of pad chars to match block size.
Or I'm doing something wrong? 

```
secKey = [55, 22, 5, 23, 11, 34, 48, 58]
decoder = pyDes.des(bytearray(secKey), pyDes.ECB, pad=b'\0')

decoded_data = decoder.decrypt(tcp_data)
```

**Comment by twhiteman** [comment]
In this case it's complaining about the *key* length (not the data).

pyDes doesn't accept bytearray's - you'll need to convert the bytearray to the bytes type, e.g.:
```
secKey = bytearray([55, 22, 5, 23, 11, 34, 48, 58])
decoder = pyDes.des(bytes(secKey), pyDes.ECB, pad=b'\0')
```
