### ISSUE TITLE
can't import pyDes 

### ISSUE THREAD

**Issue by amaresh-git-dev** [toddw-as/pyDes#16]
After installing pyDes by pip install pyDes when i am tying to import pyDes its showing some error.
![Screenshot (123)](https://user-images.githubusercontent.com/60665946/119974850-d1dea980-bfd2-11eb-9f0e-3a242974d369.png)

**Comment by toddw-as** [comment]
Try running Python in the console there and manually import pyDes - it might be a caching problem or maybe VSCode is using a different Python interpreter?

**Comment by amaresh-git-dev** [comment]
Thank you sir now its running
