### ISSUE TITLE
Create encrypted passwords for VNC?

### ISSUE THREAD

**Issue by feklee** [toddw-as/pyDes#2]
The tool [vncpassword.py][1] includes [d3des.py][2], a Python implementation of 3DES with modifications to the original 3DES algorithm. The main modification seems to be:

    # This is a departure from the original code.
    #bytebit = [ 0200, 0100, 040, 020, 010, 04, 02, 01 ] # original
    bytebit = [ 01, 02, 04, 010, 020, 040, 0100, 0200 ] # VNC version

I have no clue what that means, and I wonder: *Can I use pyDes to create 3DES encrypted passwords for VNC?*

Results of my tests:

    $ echo SomeData | tightvncpasswd -f | xxd
    0000000: 960d e668 b0d9 dd3c
    $ python3 -c "import sys; import pyDes; \
    des = pyDes.des([23, 82, 107, 6, 35, 78, 88, 7]); \
    sys.stdout.buffer.write(des.encrypt('SomeData'))" | xxd
    0000000: cd32 65aa 048d 5688                      .2e...V.
    $ python3 -c "import sys; import pyDes; \
    des = pyDes.triple_des([23, 82, 107, 6, 35, 78, 88, 7, 0, 0, 0, 0, 0, 0, 0, 0]); \
    sys.stdout.buffer.write(des.encrypt('SomeData'))" | xxd
    0000000: 23c8 ea0c bef9 ad8d                      #.......
    $ python3 -c "import sys; import pyDes; \
    des = pyDes.triple_des([23, 82, 107, 6, 35, 78, 88, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]); \
    sys.stdout.buffer.write(des.encrypt('SomeData'))" | xxd
    0000000: cd32 65aa 048d 5688                      .2e...V.

The encryption key used by VNC is `[23, 82, 107, 6, 35, 78, 88, 7]`. This is the same for TightVNC, TigerVNC, and RealVNC. Unfortunately, as you can see, with the above command lines, I'm not able to reproduce the output of the VNC password command.

[1]: https://github.com/trinitronx/vncpasswd.py
[2]: https://github.com/trinitronx/vncpasswd.py/blob/master/d3des.py

**Comment by toddw-as** [comment]
It seems that VNC is bit-flipping the password before using it in the DES algorithm.

By changing the DES key used (by bit mirroring the VNC password) it should then generate the correct result in a DES algorithm:
```
python3 -c "import sys; import pyDes; \
des = pyDes.des([232, 74, 214, 96, 196, 114, 26, 224]); \
print(des.encrypt('SomeData'))" | xxd
```

https://www.vidarholen.net/contents/junk/vnc.html

**Comment by feklee** [comment]
Thanks for figuring that out!

Anyhow, in the end took the decision to port the aforementioned `d3des.py` to Python 3 for inclusion in my tool [Vncdesk][1].

[1]:  https://github.com/feklee/vncdesk
