### ISSUE TITLE
Pydes Error generating triple des conversion

### ISSUE THREAD

**Issue by sanjusci** [toddw-as/pyDes#4]
Error: ord() expected string of length 1, but int found
I have found solution for this some changing in pyDes.py

Please change in pyDes.py file on line number 418:

if _pythonMajorVersion < 3 :

TO

if _pythonMajorVersion < 3 and isinstance(data[0], str):

**Comment by twhiteman** [comment]
Out of curiousity, what type of data are you passing into the encrypt/decrypt functions?

As normally in Python 2 it's a str (or bytes instance, which is still an instance of str).

**Comment by sanjusci** [comment]
m = SHA.new(key)
 digest = m.digest()
.
.
.
key_bytes = bytearray(key_bytes)
c = pyDes.triple_des(key_bytes, mode=pyDes.CBC, IV="\0\0\0\0\0\0\0\0", pad=None, padmode=pyDes.PAD_PKCS5)
using as above code format. It's giving an above mention error.

**Comment by sanjusci** [comment]
Please tell me where I am using wrong method in above mention code.

**Comment by twhiteman** [comment]
The workaround would be to use the original bytes object, or convert the bytearray to bytes:
```python
# key_bytes = bytearray(key_bytes) # Don't convert to bytearray
c = pyDes.triple_des(key_bytes, mode=pyDes.CBC, IV="\0\0\0\0\0\0\0\0", pad=None, padmode=pyDes.PAD_PKCS5)
```
or convert the key to bytes before passing to pyDes:
```python
key_bytes = bytearray(key_bytes)
c = pyDes.triple_des(bytes(key_bytes), mode=pyDes.CBC, IV="\0\0\0\0\0\0\0\0", pad=None, padmode=pyDes.PAD_PKCS5)
```
