### ISSUE TITLE
CBC mode adds extra bytes

### ISSUE THREAD

**Issue by linuslagerhjelm** [toddw-as/pyDes#6]
Thanks for a great implementation of DES! However, I think I may have found an issue.

**Describe your problem**
When encrypting using the DES implementation in CBC mode, the resulting output have extra bytes at the end.

**What did you expect?**
An example of correct input -> output mapping
```
KEY = b'descrypt'
STR = b'linuslag'
c = des(KEY, CBC, b"\0\0\0\0\0\0\0\0", pad=None, padmode=PAD_PKCS5)
c.encrypt(STR * 2)
# b'2u\xdb\x12\xe5-#\x9e\xe7\x8b\x99\x85M\xcc\x9a\r'
```

**What happened?**
The actual output:
```
KEY = b'descrypt'
STR = b'linuslag'
c = des(KEY, CBC, b"\0\0\0\0\0\0\0\0", pad=None, padmode=PAD_PKCS5)
c.encrypt(STR * 2)
# b'2u\xdb\x12\xe5-#\x9e\xe7\x8b\x99\x85M\xcc\x9a\r\x93\xf4w{m7#e'
```

As can be seen from these examples, the actual output is the same as the expected output except it has some extra 8 bytes at the end.

(Can be validated using online tools, such as: http://extranet.cryptomathic.com/descalc/index)

**Comment by twhiteman** [comment]
It looks like the pyDes output is correct, as your pyDes example is using the PAD_PKCS5 padding mode, which will result in a longer string (8 additional characters) when the string input length is divisible by 8.

If instead you set the padmode to be PAD_NORMAL you should get the expected result.

C.f.
https://github.com/toddw-as/pyDes/blob/master/pyDes.py#L100
https://github.com/toddw-as/pyDes/blob/master/README.md#docs-and-examples

**Comment by linuslagerhjelm** [comment]
Oh! Indeed you are right, my mistake. Terribly sorry.
